### ISSUE TITLE
arror after upgrade from `5.8.16~ynh1` to `5.8.17~ynh1`

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/pluxml_ynh#82]
i restored from backup

### Context

- Hardware: *VPS*
- YunoHost version: 
```
root@krashboyz:~# yunohost --version
yunohost: 
  repo: stable
  version: 12.0.9.1
yunohost-admin: 
  repo: stable
  version: 12.0.4
yunohost-portal: 
  repo: stable
  version: 12.0.7
moulinette: 
  repo: stable
  version: 12.0.3
ssowat: 
  repo: stable
  version: 12.0.3
```
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: `5.8.17~ynh1`
- If upgrading, current package version: *`5.8.16~ynh1`*

### Steps to reproduce

- basic upgrade
    ```sh
    # yunohost app upgrade pluxml
    ```

### Expected behavior

*A clear and concise description of what you expected to happen. You can remove this section if the command above is enough to understand your intent.*

### Logs
```
# curl -I https://eijra.krashboyz.org
HTTP/2 302 
server: nginx
date: Mon, 06 Jan 2025 13:41:37 GMT
content-type: text/html; charset=UTF-8
location: ./update/index.php
x-sso-wat: You've just been SSOed
set-cookie: PHPSESSID=es1564emft74tu3qu4fpbdcv60; path=/; domain=eijra.krashboyz.org; secure; HttpOnly
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-security-policy: upgrade-insecure-requests
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-download-options: noopen
x-permitted-cross-domain-policies: none
x-frame-options: SAMEORIGIN
permissions-policy: interest-cohort=()
strict-transport-security: max-age=63072000; includeSubDomains; preload
```
